# Generated by Django 4.2.3 on 2023-08-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outfits', '0005_stylethree_styletwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='user',
        ),
        migrations.AddField(
            model_name='styleone',
            name='category',
            field=models.CharField(default='top', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='styleone',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='clothes_pics'),
        ),
        migrations.AddField(
            model_name='styleone',
            name='name',
            field=models.CharField(default='shirt', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stylethree',
            name='category',
            field=models.CharField(default='top', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stylethree',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='clothes_pics'),
        ),
        migrations.AddField(
            model_name='stylethree',
            name='name',
            field=models.CharField(default='top', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='styletwo',
            name='category',
            field=models.CharField(default='dress', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='styletwo',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='clothes_pics'),
        ),
        migrations.AddField(
            model_name='styletwo',
            name='name',
            field=models.CharField(default='top', max_length=20),
            preserve_default=False,
        ),
    ]
